### ISSUE TITLE
NameError: name 'xrange' is not defined 

### ISSUE THREAD

**Issue by nocomp** [leonjza/ooktools#3]
hi folks,
thxx for this great tool, just a note, facing an issue on kali, first install, no issues but when i run it 
sudo ooktools signal record --frequency 433920000 --framecount 60 --destination bell.json   

i get

┌──(nocomp㉿R3dB0x)-[~/tools/sdr/ooktools]
└─$ sudo ooktools signal record --frequency 433920000 --framecount 60 --destination bell.json                       130 ⨯
         _   _           _
 ___ ___| |_| |_ ___ ___| |___
| . | . | '_|  _| . | . | |_ -|
|___|___|_,_|_| |___|___|_|___| v1.4
On-off keying tools for your SD-arrrR
https://github.com/leonjza/ooktools

Recording on frequency: 433920000 to /home/nocomp/tools/sdr/ooktools/bell.json
Configuring Radio
[radio] Frequency:     433920000
[radio] MdmModulation: 48
[radio] PktFLEN:       0
[radio] MdmDRate:      38400
[radio] MdmSyncMode:   0
[radio] Lowball:       True
For maximum frames, press and release the remote multiple times.
Traceback (most recent call last):
  File "/usr/local/bin/ooktools", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/ooktools/console.py", line 166, in record
    signalling.record(**locals())
  File "/usr/local/lib/python3.9/dist-packages/ooktools/commands/signalling.py", line 190, in record
    for c in xrange(0, framecount):
NameError: name 'xrange' is not defined
===== RESETUP set from recv thread
python3: ../../libusb/os/threads_posix.h:46: usbi_mutex_lock: Assertion `pthread_mutex_lock(mutex) == 0' failed.
zsh: abort      sudo ooktools signal record --frequency 433920000 --framecount 60  bell.json

any idea about what can be wrong?

thxx for your support

**Comment by ghost** [comment]
I have the same issue here
The only thing that resolve it sometimes is to replug the YS1 many times before it works

Any ideas ?

**Comment by gruber2000** [comment]
File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/ooktools/console.py", line 148, in search
    signalling.search(**locals())
TypeError: search() missing 1 required positional argument: 'xrange'

the same 
 :)

**Comment by diegocr** [comment]
It's 2025... how comes **nobody** bothered on fixing this in four years?

I understand this project / repo is dead / abandoned, but not even in a fork...come on guys, this is merely py2 Vs. py3 code issue 😛 

https://stackoverflow.com/a/17192181

**Comment by diegocr** [comment]
Hold... found one -> https://github.com/leonjza/ooktools/compare/master...PatWie:ooktools:master

cheers @patwie :)
